### ISSUE TITLE
Nodes frozen and increase jobs

### ISSUE THREAD

**Issue by ricarper** [filecoin-station/core#540]
The rewards froze today at 12pm, restarted at 7pm and stopped again soon after.
This situation affected all gateways. Completed jobs continue to increase but the rewards have frozen.
No error is displayed.

**Comment by juliangruber** [comment]
Yesterday there was a massive increase in Filecoin L1 chain usage, see here: https://filfox.info/en/stats/gas. Because of this, messages were stuck for a long time. Station is using a smart contract deployed to Filecoin L1 to orchestrate its services, in a trustless way. Unfortunately there isn't yet a publicly hosted Filecoin L2, which we can use. We're sorry about this interruption!
